-- Create the table to store request logs
CREATE TABLE public.function_request_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
  function_name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Add an index for faster lookups
CREATE INDEX idx_function_request_logs_user_function_time ON public.function_request_logs(user_id, function_name, created_at);

-- Enable Row Level Security (RLS) on the new table
ALTER TABLE public.function_request_logs ENABLE ROW LEVEL SECURITY;

-- Policy: Users can insert their own request logs
CREATE POLICY "Users can insert their own request logs" ON public.function_request_logs FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Policy: Users can read their own request logs
CREATE POLICY "Users can read their own request logs" ON public.function_request_logs FOR SELECT USING (auth.uid() = user_id);

-- This is a simple way to auto-delete old logs.
-- RLS policy that prevents selecting/deleting logs older than 1 hour.
-- While it doesn't auto-delete, it makes them inaccessible and easy to clean up.
-- A scheduled job is better for cleanup, but this is a simple start.
-- For now, we will rely on a scheduled function for cleanup later. 